### ISSUE TITLE
Set a default language based on a config in the instance

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/write-it#1091]
So for example in http://infoszab.writeinpublic.com would try to automatically set Hungarian as the default language.

**Comment by tmtmtmtm** [comment]
Suggested steps (via @dracos)

* Add a database column (presumably to WriteItInstanceConfig model) to store the language code for that instance
* Subclass Django's LocaleMiddleware and add a step to its process_request function to, if on an instance subdomain, add a fallback to that instance's language rather than just the LANG_CODE.
* Use that middleware rather than the built-in one.

**Comment by tmtmtmtm** [comment]
@michalskop do you already have some instances already created that you'd like us to test this with?

**Comment by michalskop** [comment]
http://plasy-2014.writeinpublic.com/
