### ISSUE TITLE
Import from json instead of PopIt

### ISSUE THREAD

**Issue by michalskop** [ciudadanointeligente/write-it#1105]
It would be useful to have possibility to import data from Popolo-standardized json file instead of PopIt. For example, if the aim is to create an instance for a city council with a couple of representatives that are not going to change in the next 4 years, setting up a new instance of PopiIt seems to me as an overkill (if all we need is to import a couple of dozens of strings).

**Comment by tmtmtmtm** [comment]
Hi @michalskop — in theory this already works like that. However, the implementation currently uses `popit-django` so it's not quite as simple as giving it the URL of the pure JSON (see the discussion at https://github.com/ciudadanointeligente/write-it/issues/1100#issuecomment-151323168)

To get the integration with WriteInPublic working, we had to write a little [proxy app](https://github.com/everypolitician/everypolitician-writeinpublic) that turned our JSON into the required format, but that was because we wanted those to automatically update any time the data changed. If it's a one-off file that would be a lot easier.

Hopefully someone will get around to replacing the dependency on `popit-django` with `django-popolo` soon though, so that even that isn't necessary,
