### ISSUE TITLE
Add page post submission

### ISSUE THREAD

**Issue by paullenz** [ciudadanointeligente/write-it#198]
Currently when the user has submitted they are taken back to the home page with just a message at the top.  Could we instead have a separate page with a strong call to action which gives the 'Check you email message' and smaller links to 'send another message' and 'view messages and replies'

**Comment by duncanparkes** [comment]
Looking at Paul's suggestion above, I don't think we want to complicate matters with links here - we reallly want the user to check their email and click the confirmation link, don't we?

**Comment by lfalvarez** [comment]
Yep! it makes total sense to just make the text a bit bigger I think.

**Comment by duncanparkes** [comment]
You mean still using the messages framework and having it go to the instance home page? I think we probably do want a separate page, just a very simple one that says little more than 'Check your email'.

**Comment by lfalvarez** [comment]
Oh! cool that makes total sense and is way simpler

**Comment by lfalvarez** [comment]
There are two links here, one is for  'Send another message' and 'View messages and replies', currently this should be pointing to the same link until we finish #453, so in the meantime I'm going to just create a single button that says "Create another message and view messages and replys".

**Comment by tmtmtmtm** [comment]
What should this page say/do if we don't need the user to click a confirmation email (e.g. if they're authenticated already)?

**Comment by lfalvarez** [comment]
I think it should simply say something like "Thanks for using Write-It" and the two previously described links

**Comment by duncanparkes** [comment]
I would say that if the user is authenticated, then I suggest we take the user back to the instance homepage with a django messaging framework type success message at the top of the page. The instance home page has new message creation and a list of current messages on it already, doesn't it?

We probably only need the intermediate success page if the message is 'Go and check your email to confirm by clicking the link' - this is too important a thing for us to get across by using the django messaging framework, because if the user doesn't do it, their message won't get sent, and the messaging framework is really for transient success/failure/info messages.

If the user needs to do an email confirmation, then prompting them to check their email needs to be the single big message of that page.

Does that all make sense?

**Comment by lfalvarez** [comment]
It absolutely does, but in the meantime we're not handling any behaviour if the user is logged in. I think we could create a separate issue while I fix this one.

**Comment by duncanparkes** [comment]
I was just thinking the same thing - the authenticated user question is something for much later when we have authenticated users :-)

**Comment by tmtmtmtm** [comment]
What do other sites do here? Would be good to look at the post-submission pages of as many other such sites as we can think of. (Attaching screenshots here would be good, if anyone is doing so...)

**Comment by lfalvarez** [comment]
I think that this should probably is already closed as we have a flow for creating messages =)

**Comment by lfalvarez** [comment]
I'm closing this as we already have a message creation wizard.
