### ISSUE TITLE
Abusive language filters

### ISSUE THREAD

**Issue by paullenz** [ciudadanointeligente/write-it#206]
How feasible is it to filter message for abusive language, and queue those selected for review via the admin screen?  Ideally able to handle multiple languages

**Comment by tmtmtmtm** [comment]
Closing for now. Can reopen if actually requested by someone.

**Comment by martinszy** [comment]
This issue was raised several times, but the use is so low that it was
never needed yet.

When implemented, I suggest that the detected messages can be moderated
instead of automatically delivered. There could be a process to communicate
with the original poster in case he wants to reform his message, and also
the administrator could be able to remove the insults and deliver the
message.

Martín.

2015-03-09 14:34 GMT+00:00 Tony Bowden <notifications@github.com>:

> Closing for now. Can reopen if actually requested by someone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciudadanointeligente/write-it/issues/206#issuecomment-77864174>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com
