### ISSUE TITLE
It should be easy to create an instance.

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/write-it#330]
Currently there is no easy way to create a new instance. There are three places where this could take place.
- [x] In the admin page
- [ ] In the user section
- [x] via the API

**Comment by tmtmtmtm** [comment]
Is what we currently have good enough in terms of functionality — i.e. all we need now is better design? Or is there any development work needed on this?

**Comment by martinszy** [comment]
The only development work I see is that it would be great to ask directly
for the popit url in the homepage, like:
¿Do you have a pop-it instance? Create your write-it now.

And after the user fills that field, we ask for this registration details,
so the registration process maybe needs to be shuffled a bit, nothing new,
but pushing some code might be necesary.

Otherwise, just provide a register button in the homepage (it's not there
now) and take the user to the your instances page where he can create his
instance. I think this is much less intuitive, but easier to code.


Martín.

2015-03-09 14:50 GMT+00:00 Tony Bowden <notifications@github.com>:

> Is what we currently have good enough in terms of functionality — i.e. all
> we need now is better design? Or is there any development work needed on
> this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciudadanointeligente/write-it/issues/330#issuecomment-77867293>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com
