### ISSUE TITLE
Simplify email templates

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#417]
Currently the subject line uses a different system `%(subject)s` to the body `{{ subject }} `

**Comment by tmtmtmtm** [comment]
The confirmation template also has a different set of substitution options: {{ confirmation.message.subject }} instead of just {{ subject }} etc.

**Comment by duncanparkes** [comment]
I think we need a much simpler system for things that can be shown in these templates. It's not reasonable to expect an instance owner to be able to come up with expressions like 

```{{ confirmation.message.content|linebreaks }}```

They're not all going to be Django coders.

Also - I'm not sure we want to allow someone to use anything they can reach from the Django templating system just because they've created an instance - this seems like a security issue to me - who knows what methods are available if you dig down from confirmation - I wouldn't be surprised if you could break out of the current instance and see other instances/users even.

I suggest we limit the template to displaying from a pre-defined selection on *strings* rather than attributes/methods of a selection of objects. We should probably also not allow the following template tags: extend, load, include, and possibly url.

In fact, the more I think about it, the less I like the idea of using the django templating system at all. How about instead using python string formatting (https://docs.python.org/2/library/string.html#format-string-syntax) with keyword arguments.

The only difficulty I can see with that as a solution on the `writeitinstance/edit/1/templates` page is how to deal with the `for` loop for the list of recipients in the confirmation messages and the `if` for whether or not a message is private. I think the solution for the private messages is simply to have separate templates for those (for now we're not worrying about private messages anyway).

Perhaps for the `for` loop of recipients we could have several pre-determined ways of displaying the list - perhaps

'recipient_names_comma_separated', 'recipient_email_addresses_comma_separated'

for the text version, and 

'recipients_as_ul' as an extra for the html version.

I'm going to park this issue and work on something else while my thoughts on it crystalize. Any suggestions welcome please!

**Comment by tmtmtmtm** [comment]
:+1: generally, though:

> for now we're not worrying about private messages anyway

That's only the WebUI — messages through the API can still be private.

**Comment by tmtmtmtm** [comment]
In general, I'd remove all logic from the templates. The primary goal here is simply to allow a basic level of customisation and/or translation of the text. If someone really wants super-fine-grained control, they can always self-host.

**Comment by duncanparkes** [comment]
Do messages through the API use the confirmation email system? Or are API users expected to deal with that kind of thing themselves?

**Comment by duncanparkes** [comment]
I agree about removing logic from the templates - perhaps just a {recipients} which produces comma separated text in the text case, and a <ul> in the html case.

**Comment by tmtmtmtm** [comment]
> Do messages through the API use the confirmation email system? Or are API users expected to deal with that kind of thing themselves?

There's an "Autoconfirm api messages" option in the Advanced tab, so I'm assuming that if that's not selected, then it does the same email-based confirmation.
