### ISSUE TITLE
Merge "Your Popit API Instances" into "Your instances"

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#444]
No need for it to have its own admin page.

**Comment by tmtmtmtm** [comment]
Actually, it should probably merge instead with the writeitinstance/edit/[id]/relate-with-popit page

**Comment by lfalvarez** [comment]
:+1:

**Comment by duncanparkes** [comment]
I'm going to assume that `accounts/my_popit_instances` is a leftover from more things being associated with the user, and not with the instance. I'll get rid of that page and merge its functionality into the instance's related popits page.

**Comment by duncanparkes** [comment]
It looks to me as though the 'Update from popit and relate' link on `accounts/my_popit_instances` does exactly the same as 'Relate a new popit api to this instance' on `en/writeitinstance/edit/2/relate-with-popit/` would do if given the url of the instance's existing popit.

I believe this means we can just remove `accounts/my_popit_instances` and make some fairly cosmetic changes to `en/writeitinstance/edit/2/relate-with-popit/` in order to get this merged.

**Comment by lfalvarez** [comment]
Agree, I think we should just remove this part =)

**Comment by lfalvarez** [comment]
closed by #560
