### ISSUE TITLE
What should an instance be called?

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#563]
We need something better than "Your instances" etc.

Current contenders: "your sites", "your WriteIts"

Ideally we'd find something better....

**Comment by zarino** [comment]
A starting point might be to think about what a WriteIt replaces. Pick a noun that sort-of describes what a WriteIt does. Are they replacements for mailing lists? Might "Your lists" make sense? Are they "boxes" (like an inbox or an outbox)? Or "groups" (because they send emails to groups of representatives)?

Maybe they're all a bit boring. It might be nice to have something with a bit of whimsy in it. I remember Photobucket used to call albums "buckets" which was really cute. Flickr called albums "pools" when they were shared across multiple authors, which is a nice word. Heroku doesn't have "processes" or "CPUs", it has "workers" and "dynos", which give you an idea of what they *do* rather than what they *are*.

Maybe people come to WriteIt to set up their own WriteIt [mailroom](http://en.wikipedia.org/wiki/Mailroom)? "Your mailrooms" – kinda cute, but I'm not sure how well it'd translate to an international audience.

**Comment by tmtmtmtm** [comment]
I like the approach. I'm wondering if it shouldn't move away from the mail metaphor entirely. Even WriteIt sounds slightly wrong to me, as this isn't just about *writing* to people (and then walking away and forgetting about it, like you can do with a petition, for example) — it's about a whole conversation being public, and permanent. And, indeed, *lots* of such conversations.

**Comment by paullenz** [comment]
random thought chatting to Tony - Town Hall (or vague similar concept)

**Comment by martinszy** [comment]
I think conversation is the key concept.
You have conversations with recipients, and the instance represents not
only the list of people that can be recipents in the conversations, but
also the record of the conversation itself.
So "forum" is one word that actually means all this, but it's already used
for software with another interaction model. "agora" is also a place that
holds conversations, also "public square" is a useful concept for
conversations about politics.

Proposals:
"Your conversation groups", "Your recipient lists",
And maybe bellow a definition: "These are the different groups of people
that are pre-defined recipients for conversations started via write-it".

I don't think I've nailed it, but I hope this helps.

Martín.

2015-03-09 12:39 GMT+00:00 paullenz <notifications@github.com>:

> random thought chatting to Tony - Town Hall (or vague similar concept)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciudadanointeligente/write-it/issues/563#issuecomment-77845729>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by tmtmtmtm** [comment]
@martinszy : Yep! 

I like Public Square too, as another thing that gets across the wider concept. We just need to come up with something snazzy that neatly encapsulates all this…

**Comment by martinszy** [comment]
what about "shoutbox" or something that resembles more of the communication
act?

martín.

2015-03-09 15:43 GMT+00:00 Tony Bowden <notifications@github.com>:

> @martinszy <https://github.com/martinszy> : Yep!
>
> I like Public Square too, as another thing that gets across the wider
> concept. We just need to come up with something snazzy that neatly
> encapsulates all this…
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciudadanointeligente/write-it/issues/563#issuecomment-77878507>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by tmtmtmtm** [comment]
"shoutbox" seems a little ranty to me — where you come to berate politicians in public, or something, rather than entering into a conversation with them...

**Comment by tmtmtmtm** [comment]
I think "Your sites" has won by default. Closing this for now. If someone comes up with something better, we'll certainly revisit it!
