### ISSUE TITLE
Run the Web Interface on WriteInPublic.com

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#570]
Give the site its own domain, so that it's easier to distinguish between the code / API server etc., and the "Connect up a PopIt and get your own site" version.

**Comment by chrismytton** [comment]
The site is now running on http://www.writeinpublic.com/en/.

**Comment by chrismytton** [comment]
Still need to setup the proper MX records for this. Because the root domain's MX records are pointed at mySociety's servers for email we need to setup MX records for i.writeinpublic.com or something similar.

**Comment by chrismytton** [comment]
Have now pointed the MX record for `i.writeinpublic.com` to the WriteIt server. However because the emails are sent in the background by celery they're all still being sent from `@writeit.ciudadanointeligente.org` addresses. I think the solution is to somehow namespace the jobs and have two sets of workers, one handling writeit emails and another handling writeinpublic.com emails.

**Comment by tmtmtmtm** [comment]
Yay, all done now!
