### ISSUE TITLE
Combine Basic update and Advanced update into a single screen

### ISSUE THREAD

**Issue by wrightmartin** [ciudadanointeligente/write-it#625]
In the manager back-end 'Basic Update' and 'Advanced update' should be a single screen, called settings.

**Comment by tmtmtmtm** [comment]
Now that there's actually something *on* the Basic Update page (the Description), is this still an issue? 

I conceptually like the idea of separating the "Things you really *should* change before putting your site live", from the "Only change these if you really know what you're doing" things, rather than throwing them all onto one page...
