### ISSUE TITLE
20035 is not a valid choice

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#715]
http://marruecos2014-3.writeit.ciudadanointeligente.org/en/write/who/ gives an error message before I've ever done anything: "Select a valid choice. 20035 is not one of the available choices."

**Comment by lfalvarez** [comment]
I think it is a slightly complex thing. What happens is that you go into an instance ie: [Eduskunta's](http://eduskunta-2.writeit.ciudadanointeligente.org/en/write/who/) you select someone let's say 'Stubb Alexander' and then you change to another WriteIt, let's say [Nouabook's](http://marruecos2014-3.writeit.ciudadanointeligente.org/en/write/who/). In the thing apparently is that it doesn't clear the session every time it changes from one WriteIt to another, so it keeps ```Stubb Alexander``` in memory in order to write an email even when changing instances.

**Comment by tmtmtmtm** [comment]
Oh, that's definitely odd. It shouldn't really be storing anything like this in the session at all — visiting /write/who should always start fresh. Closing this in favour of the wider issue: #729

**Comment by tmtmtmtm** [comment]
Reopening, as we should fix this as a cross-instance issue, rather than a within-instance issue.

**Comment by lfalvarez** [comment]
This is fixed in https://github.com/ciudadanointeligente/write-it/tree/bug/715 which is on top of https://github.com/ciudadanointeligente/write-it/tree/issues/677-dont-offer-contacts-for-whom-we-dont-have-contacts, so I think that I need to either merge #707 into master first or merge the ```bug/715``` branch into ```issues/677-dont-offer-contacts-for-whom-we-dont-have-contacts``` branch.
