### ISSUE TITLE
/write/who shouldn't remember who I'm writing to

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#729]
Visiting /write/who should be a fresh start every time — currently it remembers from somewhere who I was last writing to (even across instances! #715)

**Comment by chrismytton** [comment]
Ah yes, that makes sense. I think the fix is to override [`WizardView.get_prefix`](https://docs.djangoproject.com/en/1.6/ref/contrib/formtools/form-wizard/#django.contrib.formtools.wizard.views.WizardView.get_prefix) in `WriteMessageView` to return the name of the instance as a prefix, so the storage is kept separate.

**Comment by tmtmtmtm** [comment]
Does it need to remember at all — even within the same instance? I find it quite disconcerting to go to the page and have someone pre-selected.

**Comment by chrismytton** [comment]
It's part of the way django's form wizard works, it stores the state in the session so you can go back to the select recipients screen from the draft a message screen, or go back to the draft message screen from the preview screen and amend the message before sending.

Once you've sent a message it shouldn't then suggest the same recipients when you write a new message. If it does then that is indeed a bug.

**Comment by tmtmtmtm** [comment]
Ah, OK. Generally I dislike that sort of thing, but I can live with it here, as long as we fix it to be per-instance to avoid the #715 problem.

**Comment by tmtmtmtm** [comment]
Closing in favour of the within-instance fix #715
