### ISSUE TITLE
Make it possible to create an instance from a third party site

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#862]
e.g. EveryPolitician

**Comment by chrismytton** [comment]
I started looking at this today, specifically to replace the PopIt url on the new site screen with a list of legislatures from EveryPolitician.

The main issue is that currently PopIt is quite deeply ingrained in the way things work. So to allow importing from other sources the `Contact` model first needs to be decoupled from the PopIt `Person` model. Other things that need tackling are the `WriteItInstanceCreateForm`, which currently inherits from `WriteItInstanceCreateFormPopitUrl`, which in turn calls `load_persons_from_a_popit_api` on the `WriteItInstance`. When people are being pulled from the PopIt API a `WriteitInstancePopitInstanceRecord` represents the current state of the import ("Not doing anything now", "Error", "Success", "Waiting and In progress"), so that will also need to be removed or replaced, depending on how long we think it might take to import from EveryPolitician (I suspect probably not long enough to warrant keeping track of it in such a granular way).

The main method in the `WriteItInstance` model that does the work of actually pulling people in from popit is `relate_with_persons_from_popit_api_instance`, which calls various methods in `nuntium/popit_api_instance.py` to pull the person objects from the remote popit API into the local database and then create some `Contact` objects with the local popit `Person` object related to it.

- [ ] Make the `person` attribute on the `Contact` model polymorphic, possibly using the [contenttypes framework](https://docs.djangoproject.com/en/1.6/ref/contrib/contenttypes/).
- [ ] On the "Create your new Site" screen replace the PopIt url with a dropdown list of legislatures from EveryPolitician's [`countries.json`](https://github.com/everypolitician/everypolitician-data/blob/master/countries.json)
- [ ] Use the EP term CSV to import a terms worth of people as `Contact` instances, associated with an object that looks like a `Person` model.

**Comment by lfalvarez** [comment]
Hey! I'm sorry I'm reading this quite a few days after you created it.

So, here are my thoughts:
- I think it would be good to make some other forms of popolo available as well.
- So, what is the best approach to include all the countries as well as leave it as open for new sources of popolo formatted information?
- I really like the idea of importing CSV data from EP, would it make sense to use the ```django-popolo``` Person model ??

**Comment by chrismytton** [comment]
@lfalvarez I think it's important to note that one of the reasons for starting the EveryPolitician project was that there were *too many* different forms of popolo data. Ideally we just want to be able to import one very strict form of popolo, probably the one described on http://everypolitician.org/data_structure.html. That should hopefully make the code simpler as we won't have to allow for such a large amount of varying popolo data as we did with PopIt.

To your second point, I think the best approach is for the first version we *only* allow you to choose from a list of countries. Once we've got that solved then we can consider adding other sources in the future, as long as they follow roughly the same structure as the country level data.

To your final point, I'm not sure if we'd actually need `django-popolo`, there's only a small subset of the person data that we actually use, so perhaps a better approach would be to put all the data we need in the `Contact` model and drop the association with a `Person` entirely? This might be easier said than done though as currently the `popit.Person` model is quite deeply ingrained in the codebase.

**Comment by lfalvarez** [comment]
Hey @chrismytton !
To your first point :+1: I could not agree more.
To the second point, my only concern would be that there is a number (small still) of people that is using writeit as it currently is, and I would not like to leave them behind.
And to the final point I agree with you, specially because of the technical difficulties of including a new project into writeit. But, on the other hand I think that we need to keep an eye on ```django-popolo``` and specially of the implications that openpolis/django-popolo#18. I just mean that I rather have code that is general for a number of purposes than our own custom.

**Comment by chrismytton** [comment]
@lfalvarez Now https://github.com/ciudadanointeligente/write-it/pull/1112 has been merged it's possible to import any Popolo file which uses the same format as EveryPolitician, i.e. a generic Popolo file. So it should be possible for anyone to create a Popolo file at a url and then use that url to import the data from it.

Do you think this is enough to consider this ticket done?

**Comment by tmtmtmtm** [comment]
Other than a few issues that are separately ticketed (e.g. https://github.com/ciudadanointeligente/write-it/issues/1126, https://github.com/ciudadanointeligente/write-it/issues/1104) I think is done.
