### ISSUE TITLE
Importing data from a PopIt instance, it appear to hang and not tell you when complete

### ISSUE THREAD

**Issue by paullenz** [ciudadanointeligente/write-it#908]
I created a PopIt, imported the data (only two records) it did this, but didn't tell me and said that it was still importing - hanging.  By ignoring this and hitting "save changes" it appears to have worked, but as a user I would have sat waiting for ages

**Comment by paullenz** [comment]
![screenshot 2015-04-13 14 44 25](https://cloud.githubusercontent.com/assets/909811/7122828/e13ff80a-e1eb-11e4-813d-c59b8f6bef1a.png)

**Comment by tmtmtmtm** [comment]
Yes, this page doesn't refresh when the import completes, and we should definitely look into ways of fixing that. But I'm also hopeful that the problem will be largely hidden when creation takes you to a separate "Welcome" page, explaining what your site is etc. 

Either way, removing this problem is definitely now scheduled for tomorrow. Thanks!

**Comment by tmtmtmtm** [comment]
We can reuse the JS from `nuntium/templates/nuntium/profiles/your-instances.html` for re-checking this.
