### ISSUE TITLE
On the select a person to write to screen - search for up to five people text confusing

### ISSUE THREAD

**Issue by paullenz** [ciudadanointeligente/write-it#909]
On this screen I wasn't sure if this meant that there were five people in the instance I could write to, or what this phrase even means - would it return up to five results, could I string together five names and search for them (and if the latter, is that something I would be likely to do) - I was confused

![screenshot 2015-04-13 14 47 06](https://cloud.githubusercontent.com/assets/909811/7122856/23c32e40-e1ec-11e4-9556-69e8456945ef.png)

**Comment by paullenz** [comment]
Adding text with words to the effect - or select from the drop down below would be good as well

**Comment by tmtmtmtm** [comment]
I'm hoping this is something that @MyfanwyNixon will naturally fix tomorrow when she goes through the entire site, but suggestions very welcome! 

(For context this was added because each site can set its own limit to how many recipients a single message can go to, and the form stops you adding people after you hit that limit, which was reported as confusing by other people!)

**Comment by paullenz** [comment]
Going further in - it is now clear that I can send the same message to up to five people (or at least, that is what I think right now)

**Comment by tmtmtmtm** [comment]
Yes; we still need a complete text overhaul, including an explanation of what the site is, how it works etc.

**Comment by paullenz** [comment]
Cool - thanks!
