### ISSUE TITLE
error (get() returned more than one Contact -- it returned 2!) 

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#983]
![more than one contact 2015-04-15 at 15 40 06](https://cloud.githubusercontent.com/assets/57483/7161194/bdd74f80-e385-11e4-8bf1-893dd62202fb.png)

**Comment by equivalentideas** [comment]
I just had this as well.

**Comment by equivalentideas** [comment]
Does anyone know what this error actually means? I can't work it out from the source code sorry.

**Comment by chrismytton** [comment]
So the *reason* for the error is explained in [this StackOverflow answer](http://stackoverflow.com/a/22064255). The code that's causing the issue was quite hard to track down:

The code that actually sets the error message [is here in `nuntium/models.py`](https://github.com/ciudadanointeligente/write-it/blob/3c2ceb1a56be40326cbf4b4dca0aa7400c9f439e/nuntium/models.py#L995-L998). That gets called from [here](https://github.com/ciudadanointeligente/write-it/blob/3c2ceb1a56be40326cbf4b4dca0aa7400c9f439e/nuntium/models.py#L111) when there's an error caught. Tracing it through it appears that [this is the method which is raising the error](https://github.com/ciudadanointeligente/write-it/blob/3c2ceb1a56be40326cbf4b4dca0aa7400c9f439e/nuntium/popit_api_instance.py#L36-L67), which in turn calls [`Person.update_from_api_results` in popit-django](https://github.com/mysociety/popit-django/blob/94accb3fc38d2205f298e7177f6f1a206707288b/popit/models.py#L122).

I think the line causing the error is [this one](https://github.com/mysociety/popit-django/blob/94accb3fc38d2205f298e7177f6f1a206707288b/popit/models.py#L126), which assumes that a `popit_url` will only be used on a single write-it instance.

So we need to either add some validation to WriteIt to ensure that a datasource url can only be used by a single instance *or* we need to fix popit-django and/or remove the dependency on that library (especially since popit will be going away soon).

@equivalentideas do you have multiple WriteIt instances using the same datasource url? I think the simple workaround might be to remove the datasource from one of the WriteIt instances and they re-add it with a different url if possible.

**Comment by equivalentideas** [comment]
Thanks for tracking this down @chrismytton great work there.

> @equivalentideas do you have multiple WriteIt instances using the same datasource url?

We do indeed. We have a few test instances set up. I can set them to use a fork of the datasource so that's no problem.

We have a test site on our main user that uses the same data sources as the production site. I also have my own user that has a test site using the same data sources.

> I think the simple workaround might be to remove the datasource from one of the WriteIt instances and they re-add it with a different url if possible.

@chrismytton It's not clear to me how you remove a datasource?

Here's steps I've just gone through:

* I've switched datasources from all the test sites to update “never”.
* Fetched new data from the data source in use we want working.
* No change to the error message. I'm a bit suspicious of the status messages since it says next to it “last updated April 7, 2016, 12:20 a.m” even after I update it.
* It hasn't imported new people.
* Deleted our test site on the main user (the one with the production site)
* No change in status or recipients
* Deleted the test site on my other user
* Try fetching new data from on our production site again and ... we now seem to be back in action 🎆 . New recipients are being loaded, but no change to the status message for the data source.

Thanks for your help with this!

**Comment by henare** [comment]
@chrismytton it looks like this is now stopping us adding recipients, are you able to help remove the duplicate datasource as a workaround?

The problematic datasource is https://raw.githubusercontent.com/openaustralia/australian_local_councillors_popolo/master/nsw_local_councillor_popolo.json

We want that running on http://planningalerts.writeit.ciudadanointeligente.org/

We're not really fussed about any other instances so the datasource can most likely be removed from other instances.

**Comment by equivalentideas** [comment]
👋 Hey @chrismytton 😄 was there any action on this? We still seem to be blocked from loading new people from this data source.

**Comment by mhl** [comment]
Hi @equivalentideas - I think I can help you with this, but it might involve a bit of background. The short version is: "I think this is fixed in a new version of the codebase that's been migrated to using django-popolo instead of popit-django, but we're not quite ready to deploy that yet".

Longer version: as I'm sure you know, we are deprecating the use of PopIt, but WriteInPublic depends on it - even the EveryPolitician data is provide by a proxy that provides enough of the PopIt API for WriteInPublic. The natural migration away from PopIt, since this is a Django application, is to switch from datasources being URLs-to-PopIt-API-endpoints to URLs-to-Popolo-JSON-data, and use [mysociety-django-popolo]() instead of popit-django to provide the Person model. We've done this by adding a new component called [multiple-django-popolo-sources](https://github.com/mysociety/multiple-django-popolo-sources) to allow you to keep django-popolo models associated with a source URL, and migrating the code and data to use that. (This work is in the [migrate-to-django-popolo](https://github.com/ciudadanointeligente/write-it/pull/1181) branch.)

I've tried creating multiple instances that use the same data source URL with this new version of the codebase, and it appears to work fine - I don't get the error you report above on syncing.

As far as the progress goes in getting this significant change to the codebase deployed, I've been working with @lfalvarez to make that happen (although rather intermittently, I'm afraid, due to time constraints on both our sides). He set up a staging server with a mirror of the live writeinpublic.com database and we migrated that - that turned up a couple of problems which we fixed, but recently I found a couple of more issues that mean we'll need to try that again. So the next step in testing is to recreate that staging server and run the migration again. Then it would be great if we could get you and other users of the API to check that it's still working as expected for you.

I hope that makes sense.

**Comment by equivalentideas** [comment]
Thanks @mhl this sounds very promising :D Let us know what you need us to test and when 👍

**Comment by henare** [comment]
Hi @mhl, a council just contributed updated data for our [Ask Your Councillors](https://www.openaustraliafoundation.org.au/2016/06/21/ask-your-local-councillors/) feature on PlanningAlerts. That's the first time it's happened so we were excited to update it for them and get it live on the site. Alas I've just gone to all the trouble of doing that only to find we're still blocked by this bug :cry: 

Can you give us an idea of the likelihood that this will be fixed or a workaround provided any time soon? :wrench: It's very likely we'll be working on this feature a lot over the next couple of months so knowing this will be really useful to help us decide how WriteIt features or not in our future plans :crystal_ball:

**Comment by lfalvarez** [comment]
Hey @henare I'm checking the code and after a bit of research I found that [this particular line](https://github.com/ciudadanointeligente/write-it/blob/master/nuntium/popit_api_instance.py#L91-L94) is the one throwing the error. Somehow for the same person(ie: Prue Car) there are two contacts with the same email.
In the previous lines it picks the contact detail from an array called "contact_details" and then creates a contact. Just to understand the bug, did you ever had that array in the popolo file and then move it to "email"??
I'd say that to fix the error we would have to: 
* Add a migration that removes duplicate contacts for persons in the same PopitApiInstance
* Find in what context it created two contacts for the same person.

**Comment by henare** [comment]
> In the previous lines it picks the contact detail from an array called "contact_details" and then creates a contact. Just to understand the bug, did you ever had that array in the popolo file and then move it to "email"??

I don't _think_ we did. I've checked the history of the file and it looks like we've always used "email".

---

@lfalvarez has removed a duplicate contact for us and it's now working :tada: We're so happy to get this fixed for us - thank you Felipe! :green_heart:
